In [57]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns ,warnings
warnings.filterwarnings("ignore")
import pickle 
import tensorflow as tf
from tensorflow.keras.models import load_model

In [58]:
## load the ann model 
model = load_model('model.h5')

## load scall encode file
with open("gender_encode.pkl","rb") as file:
    gender_encode = pickle.load(file)

with open("geography_encode.pkl","rb") as file:
    geography_encode  = pickle.load(file)

with open("scale.pkl","rb") as file:
    scale  = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [59]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [60]:
geo_encode = geography_encode.transform([[input_data['Geography']]]).toarray()
geo_enocode_df = pd.DataFrame(geo_encode,columns=geography_encode.get_feature_names_out(["Geography"]))
geo_enocode_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [61]:
## convert datafeam
input_data = pd.DataFrame([input_data])
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [62]:
## combine onh data to input data
input_data = pd.concat([input_data.drop("Geography",axis=1).reset_index(drop=True),geo_enocode_df],axis=1)
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [63]:
## encode gender columns
input_data['Gender']= gender_encode.transform(input_data['Gender'])

In [64]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [65]:
## scal data
input_data = scale.transform(input_data)
input_data

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [66]:
## prediction
pred = model.predict(input_data)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
[[0.04648647]]

In [67]:
if pred > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.